#!/bin/sh
set -eu

parse entitlements-request.schema.json

format entitlements-response.schema.json \
  'entitlements=[{"capability":"integrationtest/ci/run","description":"Run the integration test suite on CI.","variables":[]}]'
