ARG DEBIAN_TAG=testing-slim
FROM debian:${DEBIAN_TAG}

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      git build-essential dpkg-dev debhelper lintian shellcheck golang-any \
 && rm -rf /var/lib/apt/lists/*

ENV GETTOKEN_DISPOSABLE_BASE=yes

WORKDIR /work
ENTRYPOINT ["sh"]
