.PHONY: setup-ubuntu-slim

setup-ubuntu-slim:
	sudo apt-get update
	sudo apt-get install -y --no-install-recommends jq bats shellcheck golang-go kcov gnupg

PLATFORM_ROOT  = $(CURDIR)
PLATFORM_BUILD = $(CURDIR)/build
PLATFORM_PATH  = /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
ON_PLATFORM    =

BASH_PARSER = /bin/bash
