.PHONY: setup-macos-26

PLATFORM_ROOT  = /Users/Shared/workspace/gettoken
PLATFORM_BUILD = /Users/mr-priviligied.guest/build
PLATFORM_PATH  = /opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin
ON_PLATFORM    = macos-vm shell env -C $(PLATFORM_ROOT)

setup-macos-26:
	$(ON_PLATFORM) brew install --no-ask jq bats-core shellcheck go kcov bash gnupg

BASH_PARSER = /opt/homebrew/bin/bash
