#!/bin/sh
set -eu

fields=$(parse ask.schema.json wants)
wants=''
eval "$fields"

request=$(format request.schema.json \
  "who=$(id -un)" \
  "doing=$(hostname)" \
  "wants=$wants" \
  signed=host-privileged)

response=$(printf '%s' "$request" | token-service)

fields=$(printf '%s' "$response" | parse response.schema.json access_token)
access_token=''
eval "$fields"

printf '%s\n' "$access_token"
