#!/bin/sh
set -eu

store=${SECRET_DIR:-/var/lib/gettoken/secrets}

fields=$(parse secret-put-request.schema.json key value)
key='' value=''
eval "$fields"

dir="$store/$key"

umask 077
mkdir -p "$dir"

held=$(find "$dir" -maxdepth 1 -type f | sed 's|.*/||' \
  | grep -E '^(0|[1-9][0-9]*)$' | sort -n | tail -1)

if [ -z "$held" ]; then
  version=0
else
  version=$((held + 1))
fi

printf '%s' "$value" > "$dir/$version"

export version value
format secret-put-response.schema.json version value
