#!/bin/bash
set -euo pipefail

exec serve \
  --request secret-get-request.schema.json \
  --request secret-get-request-version.schema.json \
  --response secret-get-response.schema.json \
  --answers "$0.answers" \
  -- "$@"
